# Generated by Django 3.2.3 on 2021-05-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_owner_pet_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
